<?php

function custom_boulder_menu () {
	$items = array();
	$items['golf/online-scorecard'] = array(
	  'title' => 'Online Scorecard',
	  'page callback' => 'custom_boulder_scorecard_page',
	  'access callback' => TRUE,
	  'type' => MENU_SUGGESTED_ITEM,
	);
	$items['golf/online-scorecard/back-nine'] = array(
	  'title' => 'Online Scorecard',
	  'page callback' => 'custom_boulder_scorecard_back_page',
	  'access callback' => TRUE,
	  'type' => MENU_SUGGESTED_ITEM,
	);
	$items['admin/photos/directory-scan'] = array(
	  'title' => 'Create Photos from a directory',
	  'page callback' => 'custom_boulder_upload_images_page',
	  'access arguments' => array('Administer Content'),
	  'type' => MENU_SUGGESTED_ITEM,
	);
	return $items;
}

function custom_boulder_scorecard_page (){
	drupal_add_js(drupal_get_path('module', 'custom_boulder').'/js/custom_boulder.js');
	drupal_add_css(drupal_get_path('module', 'custom_boulder').'/css/custom_boulder.css');
	
	$holes = db_query('SELECT * FROM holes')->fetchAll();
	$content = '
		<div id = "interactive" >
			<div id="preview_wrap">
				<div class="back_front" style="text-align:right;"><a id="show_rating" href="#">SHOW RATINGS</a><a href="/golf/online-scorecard/back-nine">BACK 9</a></div>
				<div class="ratings">
					<table>
					  <tr class="gender"><td colspan="2">Mens</td><td colspan="2">Womens</td></tr>
						<tr><td>Course</td><td>Slope</td><td>Course</td><td>Slope</td></tr>
						<tr class="td_black"><td>73.5</td><td>131</td><td></td><td></td></tr>
						<tr class="td_blue"><td>70.9</td><td>128</td><td></td><td></td></tr>
						<tr class="td_white"><td>69.1</td><td>123</td><td>75.0</td><td>136</td></tr>
						<tr class="td_gold"><td>66.3</td><td>120</td><td>71.8</td><td>122</td></tr>
						<tr class="td_red"><td></td><td></td><td>68.5</td><td>117</td></tr>
					</table>
				</div>
				<div id="preview_outer">
					<div id="preview_inner">
	';
	foreach($holes as $hole){
		if($hole->id <= 9){
		$content .= '
				<div class="scorecard">
					<img src="/'.$hole->holebigimg.'" alt="Hole #1" />
					<span>
						<img style="float:right" src="/'.$hole->holeimg.'" alt="'.$hole->title.'" />						
						<table>
							<tr><td class="td_hole" colspan="2">'.$hole->id.'</td></tr>
							<tr class="td_black"><td>Black</td><td>'.$hole->black.' yards</td></tr>
							<tr class="td_blue"><td>Blue</td><td>'.$hole->blue.' yards</td></tr>
							<tr class="td_white"><td>White</td><td>'.$hole->white.' yards</td></tr>
							<tr class="td_gold"><td>Gold</td><td>'.$hole->gold.' yards</td></tr>
							<tr class="td_red"><td>Red</td><td>'.$hole->red.' yards</td></tr>
						</table>
						<p class="par">PAR '.$hole->par.'</p>
						<p class="handicap">Handicap '.$hole->handicap.'</p>
						
						<a href="/gallery/hole-'.$hole->id.'" class="view_pics">VIEW PHOTOS</a>
					</span>
				</div>
			';
		}
	}
	$content .= 
	'
					</div>
				</div>
			</div>
			<div id="thumbs">
				<div id="arrow"></div>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_1.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_2.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_3.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_4.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_5.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_6.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_7.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_8.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_9.gif"  /></span>

			</div>
		</div>
	';
	
	return $content;

}

function custom_boulder_scorecard_back_page (){
	drupal_add_js(drupal_get_path('module', 'custom_boulder').'/js/custom_boulder.js');
	drupal_add_css(drupal_get_path('module', 'custom_boulder').'/css/custom_boulder.css');
	
	$holes = db_query('SELECT * FROM holes')->fetchAll();
	$content = '
		<div id = "interactive" >
			<div id="preview_wrap">
				<div class="back_front" style="text-align:right;"><a id="show_rating" href="#">SHOW RATINGS</a><a href="/golf/online-scorecard">Front 9</a></div>
				<div class="ratings">
					<table>
					  <tr class="gender"><td colspan="2">Mens</td><td colspan="2">Womens</td></tr>
						<tr><td>Course</td><td>Slope</td><td>Course</td><td>Slope</td></tr>
						<tr class="td_black"><td>73.5</td><td>131</td><td></td><td></td></tr>
						<tr class="td_blue"><td>70.9</td><td>128</td><td></td><td></td></tr>
						<tr class="td_white"><td>69.1</td><td>123</td><td>75.0</td><td>136</td></tr>
						<tr class="td_gold"><td>66.3</td><td>120</td><td>71.8</td><td>122</td></tr>
						<tr class="td_red"><td></td><td></td><td>68.5</td><td>117</td></tr>
					</table>
				</div>
				<div id="preview_outer">
					<div id="preview_inner">
	';
	foreach($holes as $hole){
		if($hole->id <= 18 and $hole->id > 9){
		$content .= '
				<div class="scorecard">
					<img src="/'.$hole->holebigimg.'" alt="Hole #1" />
					<span>
						<img style="float:right" src="/'.$hole->holeimg.'" alt="'.$hole->title.'" />						
						<table>
							<tr><td class="td_hole" colspan="2">'.$hole->id.'</td></tr>
							<tr class="td_black"><td>Black</td><td>'.$hole->black.' yards</td></tr>
							<tr class="td_blue"><td>Blue</td><td>'.$hole->blue.' yards</td></tr>
							<tr class="td_white"><td>White</td><td>'.$hole->white.' yards</td></tr>
							<tr class="td_gold"><td>Gold</td><td>'.$hole->gold.' yards</td></tr>
							<tr class="td_red"><td>Red</td><td>'.$hole->red.' yards</td></tr>
						</table>
						<p class="par">PAR '.$hole->par.'</p>
						<p class="handicap">Handicap '.$hole->handicap.'</p>
						
						<a href="/gallery/hole-'.$hole->id.'" class="view_pics">VIEW PHOTOS</a>
					</span>
				</div>
			';
		}
	}
	$content .= 
	'
					</div>
				</div>
			</div>
			<div id="thumbs">
				<div id="arrow"></div>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_1.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_2.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_3.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_4.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_5.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_6.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_7.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_8.gif"  /></span>
				<span><img src="/'.drupal_get_path('module', 'custom_boulder').'/images/hole_9.gif"  /></span>

			</div>
		</div>
	';
	
	return $content;
}
function custom_boulder_upload_images_page (){
	return drupal_get_form('custom_boulder_add_images_form');
}
function custom_boulder_add_images_form(){
	$form = array();
	$form['directory'] = array(
		'#title' => 'Directory where files are located',
		'#type' => 'textfield',
	);
	$form['hole'] = array(
	  '#title' => 'Select a hole to attach to all nodes created',
	  '#type' => 'textfield',
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Create Nodes',
	);
	return $form;
}
function custom_boulder_add_images_form_submit(&$form, $form_state){
	$dir = $form_state['values']['directory'];
	$mask = "/.*/";
	$files = file_scan_directory($dir, $mask, $options = array(), $depth = 0);
	foreach($files as $file2){
		$file = new StdClass();
		$file->uid = 1;
		$file->uri = $file2->uri;
		$file->filename = $file2->filename;
		$file->filemime = file_get_mimetype($file2->uri);
		$file->status = 1;
		$dest = file_default_scheme() . '://'.$form_state['values']['hole'].'/'.$file2->filename; // Subdirectory name within files directory. ($dest is optional.)     
		$file = file_copy($file, $dest);
		$file->display = 1;
		$file->description = "";

		$node = new stdClass();
		$node->type = 'gallery_image';
		node_object_prepare($node);
		$node->title = $file2->filename;
		$node->field_gallery_image['und'][0] = (array)$file;
		$node->field_image_category['und'][0]['value'] = $form_state['values']['hole'];
		node_save($node);
	}
	
}
